#build stage
FROM golang:alpine AS builder
RUN apk add --no-cache git
WORKDIR /go/src/app
COPY . .
RUN go get -d -v ./...
RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN go build -gcflags="all=-N -l" -o /go/bin/app -v ./...

#final stage
FROM alpine:latest
RUN apk --no-cache add ca-certificates docker-cli tar
COPY --from=builder /go/bin/app /app
COPY --from=builder /go/bin/dlv /dlv
RUN mkdir -p /go/src/app
COPY . /go/src/app
ENTRYPOINT ["/app"]